### ISSUE TITLE
The "Link" message needs a different name

### ISSUE THREAD

**Issue by kwan0xfff** [XplicitComputing/messages#9]
Within `concept.proto`, a `Link` message associates source and target physical systems that are being modeled. Unfortunately, in developing a software solution, a link often refers to either (1) a network link, (2) linking various binary components into an executable. That is, the term "link" is too highly overloaded. In reading any particular piece of code that consumes code generated from `concept.proto`, the context can be hard to discern.

There have been discussions about changing the "link" of modeled systems to something else. The current leading candidate is "coupling". Other terms from a thesaurus lookup included "connection", "joint", "bond", "knot"; none of these stood out as a better term. But the need for a better term than "link" seems to be accepted.

**Comment by XplicitComputing** [comment]
We'll give this a month and if there's no push-back, we'll proceed renaming Messages::Link --> Messages::Coupling
